name: automatic release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: release
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-repo
      - run: pnpm run build
      - name: Get npm tag
        id: tag
        run: |
          # Check if the tag contains "beta"
          if [[ $GITHUB_REF_NAME =~ beta ]]; then
            echo "tag=beta" >> $GITHUB_OUTPUT
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi
      - name: deploy
        run: npm i -g npm@^11.5.2 && pnpm publish --tag ${{ steps.tag.outputs.tag }} --no-git-checks
