name: automatic release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: release
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-repo
      - run: pnpm run build
      - name: deploy
        run: npm i -g npm@^11.5.2 && pnpm publish --no-git-checks
